### ISSUE TITLE
Bug: NotImplementedError() when I use MySQL

### ISSUE THREAD

**Issue by hyuma** [chanzuckerberg/sqlalchemy-aurora-data-api#2]
## Problem
```
from sqlalchemy import create_engine

cluster_arn = 'arn:aws:rds:ap-northeast-1:1234567:cluster:XXXXXXXXXXX'
secret_arn = 'arn:aws:secretsmanager:ap-northeast-1:1234567:secret:rds-db-credentials/zzzzzzzzzzzzz'


def sql():
    engine = create_engine('mysql+auroradataapi://:@/XXXXXXXXXXX',
                           echo=True,
                           connect_args=dict(aurora_cluster_arn=cluster_arn, secret_arn=secret_arn))

    with engine.connect() as conn:
        for result in conn.execute("select * from user"):
            print(result)
```

fails with `NotImplementedError` in `sqlalchemy\dialects\mysql\base.py` as follows

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Hyuma\test_aurora_sqlalchemy.py", line 25, in sql
    with engine.connect() as conn:
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\engine\base.py", line 2206, in connect
    return self._connection_cls(self, **kwargs)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\engine\base.py", line 103, in __init__
    else engine.raw_connection()
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\engine\base.py", line 2306, in raw_connection
    self.pool.unique_connection, _connection
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\engine\base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\pool\base.py", line 649, in __connect
    ).exec_once_unless_exception(self.connection, self)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\event\attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\event\attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\event\attr.py", line 322, in __call__
    fn(*args, **kw)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1485, in go
    return once_fn(*arg, **kw)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\engine\strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2374, in initialize
    self._connection_charset = self._detect_charset(connection)
  File "C:\Users\hyuma\Anaconda3\envs\general\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2784, in _detect_charset
    raise NotImplementedError()
NotImplementedError
```

## My Environment:
- Windows 10 with Python 3.7.3 64-bit
- sqlalchemy-aurora-data-api==0.1.2
- SQLAlchemy==1.3.10
- aurora-data-api==0.1.1
- boto3==1.10.5
- botocore==1.13.5
- mysqlclient==1.4.4

**Comment by kislyuk** [comment]
Thank you for your report. This issue is fixed in v0.1.3.
