### ISSUE TITLE
Bug: Postgres Numeric type fails

### ISSUE THREAD

**Issue by CorwinTanner** [chanzuckerberg/sqlalchemy-aurora-data-api#4]
First, thank you for contributing this package.

Using a `Numeric(asdecimal=True)` causes the following error:

```
Traceback (most recent call last):
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 497, in _cached_result_processor
    return dialect._type_memos[self][coltype]
KeyError: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1272, in _execute_context
    result = context.get_result_proxy()
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1126, in get_result_proxy
    return result.ResultProxy(self)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 720, in __init__
    self._init_metadata()
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 752, in _init_metadata
    self._metadata = ResultMetaData(self, cursor_description)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 240, in __init__
    textual_ordered,
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 418, in _merge_cursor_description
    for idx, (key, name, obj, type_) in enumerate(result_columns)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 418, in <listcomp>
    for idx, (key, name, obj, type_) in enumerate(result_columns)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1089, in get_result_processor
    return type_._cached_result_processor(self.dialect, coltype)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 503, in _cached_result_processor
    d[coltype] = rp = d["impl"].result_processor(dialect, coltype)
  File "/home/USER/.pyenv/versions/APP/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 666, in result_processor
    "storage." % (dialect.name, dialect.driver)
AttributeError: 'AuroraPostgresDataAPIDialect' object has no attribute 'driver'
```

I didn't include a test case due to the simplicity of the situation. You should be able to add this field to your existing test cases.

Note that this error does not occur with `asdecimal=False`.

**Comment by kislyuk** [comment]
Thank you for your report.

I am unable to reproduce your issue. I have fixed the proximate cause of the error you provided by adding the `driver` attribute and a test to ensure we have all the attributes (though not necessarily all the semantics yet) specified by the [dialect interface](https://docs.sqlalchemy.org/en/13/core/internals.html#sqlalchemy.engine.interfaces.Dialect).

I released the fix in v0.1.4. If you see further issues caused by this library, please reopen and report here.
